export const squidSpecies = [
  "Abralia (Asteroteuthis)",
  "Afrololig",
  "Alloteuthis",
  "Alloteuthis africana",
  "Alloteuthis media",
  "Alloteuthis subulata",
  "Ancistrocheiridae",
  "Ancistrocheirus",
  "Ancistroteuthis",
  "Angolan flying squid",
  "Antarctic flying squid",
  "Antarctic neosquid",
  "Arrow squid",
  "Asperoteuthis",
  "Asperoteuthis acanthoderma",
  "Asperoteuthis lui",
  "Asperoteuthis mangoldae",
  "Asperoteuthis nesisi",
  "Australiteuthidae",
  "Australiteuthis",
  "Bathothauma lyromma",
  "Bathyteuthidae",
  "Bathyteuthis",
  "Bathyteuthis abyssicola",
  "Bathyteuthoidea",
  "Batoteuthidae",
  "Batoteuthis",
  "Berryteuthis",
  "Berryteuthis anonychus",
  "Berryteuthis magister",
  "Bigfin reef squid",
  "Bigfin squid",
  "Bobtail squid",
  "Brachioteuthidae",
  "Brachioteuthis",
  "Brachioteuthis beanii",
  "Brachioteuthis behnii",
  "Brachioteuthis bowmani",
  "Brachioteuthis picta",
  "Brachioteuthis riisei",
  "Caribbean reef squid",
  "Chiroteuthidae",
  "Chiroteuthis",
  "Chiroteuthis imperator",
  "Chiroteuthis veranii",
  "Chtenopterygidae",
  "Chtenopteryx",
  "Chtenopteryx sicula",
  "Colossal squid",
  "Cranchia scabra",
  "Cranchiidae",
  "Cranchiinae",
  "Cycloteuthidae",
  "Cycloteuthis",
  "Cycloteuthis sirventi",
  "Discoteuthis",
  "Discoteuthis discus",
  "Discoteuthis laciniosa",
  "Doryteuthis",
  "Doryteuthis gahi",
  "Doryteuthis opalescens",
  "Doryteuthis plei",
  "Echinoteuthis",
  "Egea inermis",
  "Enoploteuthidae",
  "Enoploteuthis",
  "Enoploteuthis leptura",
  "European flying squid",
  "European squid",
  "Filippovia knipovitchi",
  "Firefly squi",
  "Galiteuthis",
  "Galiteuthis armata",
  "Galiteuthis glacialis",
  "Galiteuthis pacifica",
  "Galiteuthis phyllura",
  "Galiteuthis suhmi",
  "Squid giant axon",
  "Squid giant synapse",
  "Glacial squid",
  "Gonatidae",
  "Gonatopsis",
  "Gonatopsis borealis",
  "Gonatopsis japonicus",
  "Gonatopsis okutanii",
  "Gonatus",
  "Gonatus antarcticus",
  "Gonatus fabricii",
  "Gonatus onyx",
  "Grimalditeuthis",
  "Haboroteuthis",
  "Helicocranchia",
  "Helicocranchia pfefferi",
  "Heterololigo",
  "Heterololigo bleekeri",
  "Histioteuthidae",
  "Histioteuthis",
  "Histioteuthis bonnellii",
  "Histioteuthis heteropsis",
  "Histioteuthis meleagroteuthis",
  "Histioteuthis reversa",
  "Hooked squid",
  "Humboldt squidHyaloteuthis",
  "Illex",
  "Illex argentinus",
  "Illex coindetii",
  "Illex illecebrosus",
  "Illex oxygonius",
  "Illicinae",
  "Japanese flying squid",
  "Joubiniteuthidae",
  "Joubiniteuthis",
  "Joubiniteuthis portieri",
  "Lampadioteuthis",
  "Leachia",
  "Leachia cyclura",
  "Leachia danae",
  "Leachia pacifica",
  "Lepidoteuthis grimaldii",
  "Liguriella",
  "Liocranchia",
  "Liocranchia reinhardti",
  "Little flying squid",
  "Loliginidae",
  "Loligo",
  "Loligo forbesii",
  "Loligo reynaudii",
  "Loliolus",
  "Loliolus japonica",
  "Lolliguncula",
  "Lolliguncula brevis",
  "Longfin inshore squid",
  "Lycoteuthidae",
  "Lycoteuthinae",
  "Lycoteuthis",
  "Lycoteuthis lorigera",
  "Lycoteuthis springeri",
  "Magnapinna",
  "Magnapinna atlantica",
  "Magnapinna pacifica",
  "Magnapinna sp. B",
  "Magnapinna sp. C",
  "Magnapinna talismani",
  "Magnapinnidae",
  "Magnoteuthis",
  "Magnoteuthis microlucens",
  "Martialia hyadesii",
  "Mastigopsis",
  "Mastigoteuthidae",
  "Mastigotragus",
  "Megalocranchia",
  "Megalocranchia fisheri",
  "Midwater squid",
  "Moroteuthopsis",
  "Moroteuthopsis longimana",
  "Myopsida",
  "Narrowteuthis",
  "Nematolampas",
  "Nematolampas regalis",
  "Nematolampas venezuelensis",
  "Neon flying squid",
  "Neoteuthidae",
  "Neoteuthis",
  "Notonykia",
  "Notonykia africanae",
  "Notonykia nesisi",
  "Nototeuthis",
  "Octopoteuthidae",
  "Octopoteuthis",
  "Octopoteuthis danae",
  "Octopoteuthis deletron",
  "Oegopsida",
  "Ommastrephes",
  "Ommastrephes brevimanus",
  "Ommastrephidae",
  "Ommastrephinae",
  "Onychoteuthidae",
  "Onychoteuthis",
  "Onychoteuthis banksii",
  "Onychoteuthis bergii",
  "Onychoteuthis borealijaponica",
  "Onychoteuthis compacta",
  "Onychoteuthis meridiopacifica",
  "Onykia",
  "Onykia appelloefi",
  "Onykia carriboea",
  "Onykia ingens",
  "Onykia loennbergii",
  "Onykia robsoni",
  "Onykia robusta",
  "Ornithoteuthis",
  "Ornithoteuthis antillarum",
  "Ornithoteuthis volatilis",
  "Parateuthis",
  "Pholidoteuthidae",
  "Pholidoteuthis",
  "Pickfordiateuthis",
];
